# Generated by Django 4.2.30 on 2026-06-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('contrasena', models.CharField(max_length=200)),
                ('nombre_negocio', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20)),
                ('licencia', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nombre_negocio', 'Cambio de nombre del negocio'), ('puesto', 'Cambio de puesto'), ('descripcion', 'Cambio de descripción'), ('ubicacion', 'Cambio de ubicación')], max_length=40)),
                ('valor_nuevo', models.TextField()),
                ('aprobada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatarios.locatario')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatarios.locatario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatarios.locatario')),
            ],
        ),
    ]
