# Generated by Django 5.1.15 on 2026-06-22 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locatario',
            name='foto_local',
            field=models.ImageField(blank=True, null=True, upload_to='locales/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='valor_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cambios_pendientes/'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='tipo',
            field=models.CharField(choices=[('nombre_negocio', 'Cambio de nombre del negocio'), ('puesto', 'Cambio de puesto'), ('descripcion', 'Cambio de descripción'), ('ubicacion', 'Cambio de ubicación'), ('foto_perfil', 'Cambio de foto del locatario'), ('foto_local', 'Cambio de foto del local')], max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='valor_nuevo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatarios.locatario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('puesto', models.CharField(blank=True, max_length=80)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatarios.locatario')),
            ],
        ),
    ]
